ARG PGADMIN_VERSION
FROM docker.io/dpage/pgadmin4:${PGADMIN_VERSION}
LABEL MAINTAINER Justin Zhang "schnell18@gmail.com"

# switch back to root to ease file sharing between container and host
USER root