# dockerized virtual environment
version: '3.9'
services:

  powerjob:
    image: docker.io/schnell18/powerjob-server:4.0.1-hf05-amd64
    restart: always
    healthcheck:
      test: "nc -z localhost 7700"
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "job_scheduler=true"
    environment:
      - JVM_XMS=1024m
      - JVM_XMX=1024m
      - JVM_XMN=512m
      - SPRING_PROFILES_ACTIVE=localenv
      - SPRING_DATASOURCE_CORE_JDBC-URL=jdbc:mysql://mariadb:3306/powerjob?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_CORE_USERNAME=mfg
      - SPRING_DATASOURCE_CORE_PASSWORD=abc
      - OMS_MONGODB_ENABLE=false
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "7700:7700"
      - "10086:10086"
    volumes:
      - ./.state/powerjob/logs:/powerjob/logs
