# dockerized virtual environment
version: '3.9'

services:

  nginx:
    image: nginx:1.20.1-alpine
    restart: always
    healthcheck:
      test: "nc -z localhost 80"
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 15
    volumes:
      - ./provision/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80/tcp"

