# dockerized virtual environment
version: '3.9'

services:

  haydn:
    build:
      context: ./backends/haydn/
      dockerfile: Dockerfile-virtualenv
      extra_hosts:
        - "tinker.cf:192.168.31.25"
    image: schnell18/haydn:latest
    restart: always
    healthcheck:
      test: "nc -z localhost 29000"
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      mariadb:
        condition: service_healthy
      redis-cnode1:
        condition: service_healthy
    volumes:
      - ./provision/apps/haydn/configs:/data/conf
    ports:
      - "24003:29000"
      - "8083:28000"

  haydn-job-agent:
    image: schnell18/powerjob-agent:4.0.1-hf04-amd64
    restart: always
    healthcheck:
      test: "nc -z localhost 27777"
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
      PARAMS: --app=haydn --server=powerjob:7700
    depends_on:
      powerjob:
        condition: service_healthy
      # haydn:
      #   condition: service_healthy
    volumes:
      - ./.state/haydn/powerjob-agent:/powerjob/logs
    ports:
      - "27777:27777"
