# dockerized virtual environment
version: '3.9'
services:

  etcd:
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    healthcheck:
      test: "curl -s http://127.0.0.1:2379/health | jq .health | grep true"
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 15
    volumes:
      - ./.state/etcd/data:/etcd_data
      - ./provision/etcd/conf:/opt/bitnami/etcd/conf/
    environment:
      - ETCD_CONFIG_FILE=/opt/bitnami/etcd/conf/etcd.conf.yml
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379/tcp"
