# dockerized virtual environment
version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    labels:
      - "mq_broker=true"
    volumes:
      - ./.state/rabbitmq:/var/lib/rabbitmq
