version: '3.9'
services:

  kafka1:
    image: schnell18/kafka:3.1.0-1-alpine-amd64
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    depends_on:
      zookeeper1:
        condition: service_healthy
    environment:
      - MAX_HEAP_SIZE=256m
    volumes:
      - ./provision/kafka/common/log4j.properties:/kafka/config/log4j.properties
      - ./provision/kafka/broker1/server.properties:/kafka/config/server.properties
      - ./.state/kafka/broker1/data:/var/lib/kafka/data
      - ./.state/kafka/broker1/logs:/var/lib/kafka/logs
    ports:
      - "9092:9092"
    restart: on-failure

  kafka2:
    image: schnell18/kafka:3.1.0-1-alpine-amd64
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    depends_on:
      zookeeper1:
        condition: service_healthy
    environment:
      - MAX_HEAP_SIZE=256m
    volumes:
      - ./provision/kafka/common/log4j.properties:/kafka/config/log4j.properties
      - ./provision/kafka/broker2/server.properties:/kafka/config/server.properties
      - ./.state/kafka/broker2/data:/var/lib/kafka/data
      - ./.state/kafka/broker2/logs:/var/lib/kafka/logs
    ports:
      - "9093:9092"
    restart: on-failure

  kafka3:
    image: schnell18/kafka:3.1.0-1-alpine-amd64
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    depends_on:
      zookeeper1:
        condition: service_healthy
    environment:
      - MAX_HEAP_SIZE=256m
    volumes:
      - ./provision/kafka/common/log4j.properties:/kafka/config/log4j.properties
      - ./provision/kafka/broker3/server.properties:/kafka/config/server.properties
      - ./.state/kafka/broker3/data:/var/lib/kafka/data
      - ./.state/kafka/broker3/logs:/var/lib/kafka/logs
    ports:
      - "9094:9092"
    restart: on-failure
