version: '3.9'
services:

  kafka1:
    image: docker.io/schnell18/kafka:4.0.0-8-alpine
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      # - ./provision/kafka4/common/log4j2.properties:/opt/kafka/config/log4j2.properties
      - ./provision/kafka4/node1/kraft:/opt/kafka/config/kraft
      - ./.state/kafka4/node1/data:/tmp/kraft-combined-logs
      - ./.state/kafka4/node1/logs:/opt/kafka/logs
    ports:
      - "9092:9092"
    restart: on-failure

  kafka2:
    image: docker.io/schnell18/kafka:4.0.0-8-alpine
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      # - ./provision/kafka4/common/log4j2.properties:/opt/kafka/config/log4j2.properties
      - ./provision/kafka4/node2/kraft:/opt/kafka/config/kraft
      - ./.state/kafka4/node2/data:/tmp/kraft-combined-logs
      - ./.state/kafka4/node2/logs:/opt/kafka/logs
    ports:
      - "9093:9092"
    restart: on-failure

  kafka2:
    image: docker.io/schnell18/kafka:4.0.0-8-alpine
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      # - ./provision/kafka4/common/log4j2.properties:/opt/kafka/config/log4j2.properties
      - ./provision/kafka4/node3/kraft:/opt/kafka/config/kraft
      - ./.state/kafka4/node3/data:/tmp/kraft-combined-logs
      - ./.state/kafka4/node3/logs:/opt/kafka/logs
    ports:
      - "9094:9092"
    restart: on-failure

  kafka-ui:
    container_name: kafka-ui
    image: docker.io/provectuslabs/kafka-ui:v0.7.2
    ports:
      - 9000:8080
    depends_on:
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      SERVER_SERVLET_CONTEXT_PATH: /kafkaui
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: abc

  # kafdrop:
  #   image: docker.io/schnell18/kafdrop:4.1.0-3-alpine
  #   # image: docker.io/obsidiandynamics/kafdrop:3.29.0
  #   healthcheck:
  #     test: "nc -z localhost 9000"
  #     start_period: 20s
  #     interval: 30s
  #     timeout: 10s
  #     retries: 15
  #   depends_on:
  #     kafka1:
  #       condition: service_healthy
  #     # kafka2:
  #     #   condition: service_healthy
  #     # kafka3:
  #     #   condition: service_healthy
  #   command: obsidiandynamics/kafdrop
  #   environment:
  #     # KAFKA_BROKER_CONNECT: "kafka1:9092,kafka2:9092,kafka3:9092"
  #     KAFKA_BROKERCONNECT: "kafka1:9092"
  #     JVM_OPTS: "-Xms32M -Xmx64M"
  #     SERVER_SERVLET_CONTEXTPATH: "/"
  #   volumes:
  #     - ./provision/kafka4/kafdrop:/config
  #   ports:
  #     - "9000:9000"
  #   restart: on-failure
