version: '3.9'
services:

  kafka1:
    image: quay.io/schnell18/kafka:4.0.0-3-alpine
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      # - ./provision/kafka4/common/log4j2.properties:/opt/kafka/config/log4j2.properties
      # - ./provision/kafka4/broker3/server.properties:/opt/kafka/config/server.properties
      - ./.state/kafka4/broker1/data:/tmp/kraft-combined-logs
      - ./.state/kafka4/broker1/logs:/opt/kafka/logs
    ports:
      - "9092:9092"
    restart: on-failure

  kafka2:
    image: quay.io/schnell18/kafka:4.0.0-3-alpine
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      # - ./provision/kafka4/common/log4j2.properties:/opt/kafka/config/log4j2.properties
      # - ./provision/kafka4/broker2/server.properties:/opt/kafka/config/server.properties
      - ./.state/kafka4/broker2/data:/tmp/kraft-combined-logs
      - ./.state/kafka4/broker2/logs:/opt/kafka/logs
    ports:
      - "9093:9092"
    restart: on-failure

  kafka3:
    image: quay.io/schnell18/kafka:4.0.0-3-alpine
    healthcheck:
      test: "nc -z localhost 9092"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      # - ./provision/kafka4/common/log4j2.properties:/opt/kafka/config/log4j2.properties
      # - ./provision/kafka4/broker3/server.properties:/opt/kafka/config/server.properties
      - ./.state/kafka4/broker3/data:/tmp/kraft-combined-logs
      - ./.state/kafka4/broker3/logs:/opt/kafka/logs
    ports:
      - "9094:9092"
    restart: on-failure

  kafdrop:
    image: docker.io/obsidiandynamics/kafdrop:4.1.0
    healthcheck:
      test: "nc -z localhost 9000"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    depends_on:
      kafka1:
        condition: service_healthy
    command: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092,kafka2:9092,kafka3:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    ports:
      - "9000:9000"
    restart: on-failure
