# dockerized virtual environment
version: '3.9'

services:

  # monitors
  pushgateway:
    image: docker.io/prom/pushgateway:v1.4.2
    command:
      - --log.level=error
    restart: on-failure

  prometheus:
    user: root
    image: docker.io/prom/prometheus:v2.32.1
    restart: on-failure
    command:
      - --log.level=error
      - --storage.tsdb.path=/data/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./provision/prometheus/config:/etc/prometheus:ro
      - ./.state/prometheus/data:/data

  nodeexporter:
    image: docker.io/prom/node-exporter:v1.3.1
    restart: on-failure
    ports:
      - "9100:9100"

