# dockerized virtual environment
version: '3.9'
services:

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.32
    healthcheck:
      test: "nc -z localhost 16687"
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 15
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14267"
      - "14268:14268"
      - "14269"
      - "16686:16686"
      - "16687"
      - "9411:9411"
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://es01:9200"

