# dockerized virtual environment
version: '3.9'

# x-podman:
#   in_pod: false

services:
  rabbitmq:
    # image: docker.io/rabbitmq:3.9.11-management-alpine
    # userns_mode: keep-id
    image: docker.io/schnell18/rabbitmq:4.1.0-management-alpine-1
    healthcheck:
      test: "nc -z localhost 5672"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      RABBITMQ_DEFAULT_USER: localenv
      RABBITMQ_DEFAULT_PASS: localenv
    ports:
      - 5672:5672
      - 15672:15672
    labels:
      - "mq_broker=true"
    volumes:
      - type: bind
        source: .state/rabbitmq
        target: /var/lib/rabbitmq
        options: "z,U=1000,G=1000"
      - type: bind
        source: .infra/global/etc/localtime
        target: /etc/localtime
      - type: bind
        source: .infra/global/etc/timezone
        target: /etc/timezone
    security_opt:
      - label=disable
