# dockerized virtual environment
version: '3.9'
services:

  # init:
  #   image: docker.io/schnell18/mariadb:10.7-focal-2
  #   command: >
  #     bash -c "
  #         echo 'Prepare database nacos ...' &&
  #         sh /setup/create-database.sh nacos mfg &&
  #         echo 'Loading schema and data for nacos ...' &&
  #         sh /setup/load-schema-and-data.sh nacos mfg nacos .infra"
  #   volumes:
  #     - ../../:/work
  #     - ./provision/setup:/setup
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy

  nacos:
    image: docker.io/schnell18/nacos-server:1.4.2-alpine
    # image: docker.io/nacos/nacos-server:2.0.3-slim
    healthcheck:
      # test: "cat /proc/1/cmdline | grep nacos"
      test: "nc -z localhost 8848"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
      - JVM_MS=64m
      - JVM_MMS=80m
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mariadb
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=localenv
      - MYSQL_SERVICE_PASSWORD=localenv
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    volumes:
      - ../../.state/nacos/standalone-logs/:/home/nacos/logs
      - ../nacos/provision/init.d:/home/nacos/init.d
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
