# dockerized virtual environment
version: '3.9'

services:

  mariadb:
    image: docker.io/mariadb:10.7-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mfg
      MYSQL_PASSWORD: abc
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute 'SHOW DATABASES;'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    labels:
      - "dbtype=MariaDB"
      - "database=true"
    volumes:
      - ../../:/work
      - ./provision/conf.d:/etc/mysql/conf.d
      - ./provision/setup:/setup
      - ../../.state/mariadb/data:/var/lib/mysql

