# dockerized virtual environment
version: '3.9'

services:

  cockroachdb-1:
    image: docker.io/schnell18/cockroachdb:v25.2.4-3
    hostname: cockroachdb-1
    restart: always
    healthcheck:
      test: "cockroach sql --insecure --host=cockroachdb-1:26257 -e='SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26257:26257"  # SQL port
      - "8080:8080"    # Admin UI port
    labels:
      - "dbtype=CockroachDB"
      - "database=true"
      - "cluster-node=1"
    volumes:
      - ../../:/work
      - ../../.state/cockroachdb/node1:/cockroach/cockroach-data
    entrypoint: >
      sh -c "
        cockroach start \
          --insecure \
          --advertise-addr=cockroachdb-1:26257 \
          --http-addr=cockroachdb-1:8080 \
          --listen-addr=cockroachdb-1:26257 \
          --join=cockroachdb-1:26257,cockroachdb-2:26258,cockroachdb-3:26259 \
          --background;
        echo '⏳ Waiting for other nodes...';
        sleep 10;
        echo '🚀 Initializing CockroachDB cluster...';
        cockroach init --insecure --host=cockroachdb-1:26257;
        echo '⏳ Waiting for CockroachDB cluster to be ready...';
        until cockroach sql --insecure --host=cockroachdb-1:26257 -e 'SELECT 1;' >/dev/null 2>&1; do
          sleep 2;
        done;
        echo '✅ CockroachDB cluster is up, creating localenv super user...';
        cockroach sql --insecure --host=cockroachdb-1:26257 \
          -e \"CREATE USER IF NOT EXISTS localenv;\" \
          -e \"GRANT admin TO localenv;\" \
          -e \"GRANT ALL ON DATABASE defaultdb TO localenv;\";
        echo '🎉 User localenv created with admin rights';
        tail -f /dev/null;
      "

  cockroachdb-2:
    image: docker.io/schnell18/cockroachdb:v25.2.4-3
    hostname: cockroachdb-2
    restart: always
    healthcheck:
      test: "cockroach sql --insecure --host=cockroachdb-2:26257 -e='SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26258:26258"  # SQL port
      - "8081:8081"    # Admin UI port
    labels:
      - "dbtype=CockroachDB"
      - "database=true"
      - "cluster-node=2"
    volumes:
      - ../../:/work
      - ../../.state/cockroachdb/node2:/cockroach/cockroach-data
    depends_on:
      - cockroachdb-1
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for first node...';
        sleep 15;
        cockroach start \
          --insecure \
          --advertise-addr=cockroachdb-2:26258 \
          --http-addr=cockroachdb-2:8081 \
          --listen-addr=cockroachdb-2:26258 \
          --join=cockroachdb-1:26257,cockroachdb-2:26258,cockroachdb-3:26259 \
          --background;
        echo '✅ CockroachDB node 2 started';
        tail -f /dev/null;
      "

  cockroachdb-3:
    image: docker.io/schnell18/cockroachdb:v25.2.4-3
    hostname: cockroachdb-3
    restart: always
    healthcheck:
      test: "cockroach sql --insecure --host=cockroachdb-3:26259 -e='SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26259:26259"  # SQL port
      - "8082:8082"    # Admin UI port
    labels:
      - "dbtype=CockroachDB"
      - "database=true"
      - "cluster-node=3"
    volumes:
      - ../../:/work
      - ../../.state/cockroachdb/node3:/cockroach/cockroach-data
    depends_on:
      - cockroachdb-1
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for first node...';
        sleep 20;
        cockroach start \
          --insecure \
          --advertise-addr=cockroachdb-3:26259 \
          --http-addr=cockroachdb-3:8082 \
          --listen-addr=cockroachdb-3:26259 \
          --join=cockroachdb-1:26257,cockroachdb-2:26258,cockroachdb-3:26259 \
          --background;
        echo '✅ CockroachDB node 3 started';
        tail -f /dev/null;
      "
