# dockerized virtual environment
version: '3.9'

services:

  cockroachdb:
    image: docker.io/schnell18/cockroachdb:v25.2.4-2
    restart: always
    healthcheck:
      test: "cockroach sql --insecure -e='SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26257:26257"  # SQL port
      - "8080:8080"    # Admin UI port
    labels:
      - "dbtype=CockroachDB"
      - "database=true"
    volumes:
      - ../../:/work
      - ../../.state/cockroachdb/data:/cockroach/cockroach-data
    entrypoint: >
      sh -c "
        cockroach start-single-node --insecure --host=0.0.0.0 --background;
        echo 'â³ Waiting for CockroachDB to be ready...';
        until cockroach sql --insecure -e 'SELECT 1;' >/dev/null 2>&1; do
          sleep 2;
        done;
        echo 'âœ… CockroachDB is up, creating localenv super user...';
        cockroach sql --insecure \
          -e \"CREATE USER IF NOT EXISTS localenv;\" \
          -e \"GRANT admin TO localenv;\" \
          -e \"GRANT ALL ON DATABASE defaultdb TO localenv;\";
        echo 'ðŸŽ‰ User localenv created with admin rights';
        tail -f /dev/null;
      "
