# dockerized virtual environment
version: '3.9'

services:

  cockroachdb:
    image: docker.io/schnell18/cockroachdb:v25.2.4-1
    restart: always
    healthcheck:
      test: "cockroach sql --insecure -e='SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26257:26257"  # SQL port
      - "8080:8080"    # Admin UI port
    labels:
      - "dbtype=CockroachDB"
      - "database=true"
    volumes:
      - ../../:/work
      - ../../.state/cockroachdb/data:/cockroach/cockroach-data
  cockroachdb-init:
    image: docker.io/schnell18/cockroachdb:v25.2.4-1
    depends_on:
      - cockroachdb
    restart: "no"
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for CockroachDB...';
        until cockroach sql --insecure --host=cockroachdb:26257 -e 'SELECT 1;' >/dev/null 2>&1; do
          sleep 2;
        done;
        echo '✅ CockroachDB is up, creating user...';
        cockroach sql --insecure --host=cockroachdb:26257 \
          -e \"CREATE USER IF NOT EXISTS localenv;\" \
          -e \"GRANT admin TO localenv;\" \
          -e \"GRANT ALL ON DATABASE defaultdb TO localenv;\";
        echo '🎉 User localenv created with admin rights';
      "
