version: '3.9'

services:

  fluentbit:
    image: docker.io/fluent/fluent-bit:3.2.10-debug
    healthcheck:
      test: "nc -z localhost 24224"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ../global/etc/localtime:/etc/localtime
      - ../global/etc/timezone:/etc/timezone
      - ./provision/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ../../.state/fluentbit/logs-vol:/logs

  buzz:
    image: busybox:latest
    command: |
      sh -c '
      while true; do
          echo "Greeting from buzz on $(date -Iseconds)!!!"
          sleep 1
      done'
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: buzz
