ARG POSTGRESQL_VERSION
FROM docker.io/postgres:${POSTGRESQL_VERSION}
LABEL MAINTAINER Justin Zhang "schnell18@gmail.com"

# switch back to root to ease file sharing between container and host
USER root