filebeat.inputs:
- type: log
  enabled: true
  scan_frequency: 3
  clean_removed: true
  paths:
  - /usr/share/filebeat/logs/**/*.log

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:es01:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
