# dockerized virtual environment
version: '3.9'

services:
  titra:
    image: docker.io/kromit/titra:0.79.3
    container_name: titra
    healthcheck:
      test: "nc -z localhost 3000"
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://root:root@mongodb/titra?directConnection=true&authSource=admin
      - ROOT_URL=http://localhost:3000
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
