# dockerized virtual environment
version: '3.9'

services:

  mongodb:
    image: docker.io/schnell18/mongodb:4.4.14-2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: localenv
      MONGO_INITDB_ROOT_PASSWORD: localenv
    healthcheck:
      test: "/usr/bin/mongo -ulocalenv -plocalenv --eval 'version()'"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
    labels:
      - "dbtype=mongodb"
      - "database=true"
    volumes:
      - ../../:/work
      - ../../.state/mongodb/data:/data/db
