name: build-and-push-docker-image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push golang build alpine
        uses: docker/build-push-action@v3
        with:
          context: ./Containerfiles/golang/build/alpine/1.19/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/schnell18/golang-build:latest
