name: build-and-push-docker-image

on:
  push:
    branches:
      - 'master'
      - 'podman'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build Image
      id: build-image-golang-build-119
      uses: redhat-actions/buildah-build@v2
      with:
        image: golang-build
        tags: latest ${{ github.sha }}
        archs: amd64, arm64
        containerfiles: |
          ./Containerfiles/golang/build/alpine/1.19/Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image-golang-build-119.outputs.image }}
        tags: ${{ steps.build-image-golang-build-119.outputs.tags }}
        registry: quay.io/${{ secrets.REGISTRY_USERNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
