name: etcd

on:
  push:
    branches:
      - 'master'
      - 'podman'
    paths:
      - Containerfiles/etcd/Dockerfile
      - Containerfiles/etcd/version.json

jobs:
  build:
    name: Build and push image
    environment: production
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Get ETCD version
        id: etcd-version
        run: |
          echo -n ::set-output name=ETCD_VERSION::
          jq -r '.etcdVersion' Containerfiles/etcd/version.json

      - name: Get build number
        id: build-number
        run: |
          echo -n ::set-output name=BUILD_NO::
          jq -r '.build' Containerfiles/etcd/version.json

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: etcd
          build-args: |
            ETCD_VERSION=${{ steps.etcd-version.outputs.ETCD_VERSION }}
          tags: ${{ steps.etcd-version.outputs.ETCD_VERSION }}-${{ steps.build-number.outputs.BUILD_NO }}-alpine
          archs: amd64, arm64
          context: Containerfiles/etcd/
          containerfiles: Containerfiles/etcd/Dockerfile

      - name: Push To docker.io
        id: push-to-docker
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io/${{ secrets.REGISTRY_USERNAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-docker.outputs.registry-paths }}"
