name: kafdrop

on:
  push:
    branches:
      - 'master'
    paths:
      - Containerfiles/kafdrop/Dockerfile
      - Containerfiles/kafdrop/version.json

jobs:
  build:
    name: Build and push image
    environment: production
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Get JRE runtime iamge tag
      id: jre-rt-image-tag
      run: |
        echo -n ::set-output name=JRE_RT_IMG_TAG::
        jq -r '.jreRuntimeImageTag' Containerfiles/kafdrop/version.json

    - name: Get kafdrop version
      id: kafdrop-version
      run: |
        echo -n ::set-output name=KAFDROP_VERSION::
        jq -r '.kafdropVersion' Containerfiles/kafdrop/version.json

    - name: Get build number
      id: build-number
      run: |
        echo -n ::set-output name=BUILD_NO::
        jq -r '.build' Containerfiles/kafdrop/version.json

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: kafdrop
        build-args: |
          KAFDROP_VERSION=${{ steps.kafdrop-version.outputs.KAFDROP_VERSION }}
          JRE_RUNTIME_IMG_TAG=${{ steps.jre-rt-image-tag.outputs.JRE_RT_IMG_TAG }}
        tags: ${{ steps.kafdrop-version.outputs.KAFDROP_VERSION }}-${{ steps.build-number.outputs.BUILD_NO }}-alpine
        archs: amd64, arm64
        context: Containerfiles/kafdrop/
        containerfiles: Containerfiles/kafdrop/Dockerfile

    - name: Push To docker.io
      id: push-to-docker
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags:  ${{ steps.build-image.outputs.tags }}
        registry: docker.io/${{ secrets.REGISTRY_USERNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-docker.outputs.registry-paths }}"
